project:
  type: website

website:
  title: "G.I.A.N. (Gian's Ideas and Notes)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

